### ISSUE TITLE
recover_profile declares type variable FT but does not use it.

### ISSUE THREAD

**Issue by simonbyrne** [CliMA/SurfaceFluxes.jl#108]
I get the following warning in Julia 1.9:
```
WARNING: method definition for recover_profile at /Users/simon/.julia/packages/SurfaceFluxes/wxPUw/src/SurfaceFluxes.jl:882 declares type variable FT but does not use it.
```
Linked method is here:
https://github.com/CliMA/SurfaceFluxes.jl/blob/ca78057c645aa61293b27416c687962a83e2d661/src/SurfaceFluxes.jl#L882-L904

**Comment by akshaysridhar** [comment]
Cleaning up some of this in #82. Will ping for review when ready.

**Comment by akshaysridhar** [comment]
@sriharshakandala I think we can close this now
