### ISSUE TITLE
Land-model evaporation (mismatch with data-comparison)

### ISSUE THREAD

**Issue by akshaysridhar** [CliMA/SurfaceFluxes.jl#131]
Review model computations of SHF / evap in big-leaf + soil model. 
This issue aims to track any investigations / assessment of the SurfaceFluxes.jl package as it relates to this big-leaf model. 

Reference images: 
<img width="480" alt="Screenshot 2023-10-06 at 11 21 53 AM" src="https://github.com/CliMA/SurfaceFluxes.jl/assets/43710045/8e4a53bd-3a9f-4a6c-9572-8b2011c5f662">

<img width="537" alt="Screenshot 2023-10-06 at 11 22 10 AM" src="https://github.com/CliMA/SurfaceFluxes.jl/assets/43710045/b3d82b6a-46d5-43bd-9ee2-aa442b5c60a6">

cc @kmdeck @braghiere 

Tracking this issue following the sprint meeting here.

**Comment by braghiere** [comment]
More info here: https://github.com/CliMA/ClimaLSM.jl/pull/341#issuecomment-1751491158

Latent heat looks ok, but sensible heat is still very wrong:
![lhf](https://github.com/CliMA/SurfaceFluxes.jl/assets/23744195/dc8aeee7-4c64-4184-881a-1a6956b18e08)

![shf](https://github.com/CliMA/SurfaceFluxes.jl/assets/23744195/1d75016c-145c-42f0-9cbc-0c6b70b60283)

**Comment by akshaysridhar** [comment]
See also https://github.com/CliMA/ClimaLSM.jl/pull/362 : `bare soil evaporation` experiment.

**Comment by akshaysridhar** [comment]
@kmdeck is the root-cause well understood now ? Can we close this issue ?

**Comment by kmdeck** [comment]
yep! and im working on the bare soil stuff in a separate PR, but that is almost certainly not SF related
