### ISSUE TITLE
bors is no longer supported - switch CI / merge checks to Github merge-queues

### ISSUE THREAD

**Issue by akshaysridhar** [CliMA/SurfaceFluxes.jl#135]
`bors` is no longer supported. This means we need to switch the CI pipelines to use either 

1. [github merge queues](https://github.blog/2023-07-12-github-merge-queue-is-generally-available/)
2. requiring branches to be up-to-date before merging

SurfaceFluxes is currently likely to be considered a low-commit repository. Thus, option (2) might suffice. 
cc @sriharshakandala @Sbozzolo

**Comment by Sbozzolo** [comment]
I am going this move your repo to 2. if you don't have objections. You'll have to use the GitHub button to merge your changes.

**Comment by akshaysridhar** [comment]
> I am going this move your repo to 2. if you don't have objections. You'll have to use the GitHub button to merge your changes.

This is reasonable. Thanks!

**Comment by Sbozzolo** [comment]
I changed the settings and update some files. Can you try the new workflow by adding a PR that removes `bors.toml`?

**Comment by Sbozzolo** [comment]
(First the other PR has to be merged)

**Comment by akshaysridhar** [comment]
Waiting for https://github.com/CliMA/SurfaceFluxes.jl/pull/136 to merge following which I'll try the new workflow as mentioned above.

**Comment by akshaysridhar** [comment]
@Sbozzolo can confirm new workflow introduces the following changes
(1) PR commits trigger CI-builds. 
(2) Requires manual 'merge' once checks have passed. We'll require squashed commits prior to merge as part of the review process.

**Comment by Sbozzolo** [comment]
You can click on "Enable auto-merge" before the tests have completed.

**Comment by Sbozzolo** [comment]
If you do so, the PR will be merged if the tests pass.
