### ISSUE TITLE
GPU tests do not populate the output correctly.

### ISSUE THREAD

**Issue by charleskawczynski** [CliMA/SurfaceFluxes.jl#142]
I'm not sure when this happened, but the gpu test tests that the Float64 and Float32 results are approximately the same. First, it'd probably be better if we test both of these against a CPU implementation, better yet, hard code results.

The existing gpu tests look like they should populate a 4 element array, but then only the first element is populated, which means that the gpu test is just wrong. That is to say: for `ii = @index(Group, Linear)`, `ii` should span 1:4, but it's only ever 1.

cc @Sbozzolo, @akshaysridhar

**Comment by akshaysridhar** [comment]
@charleskawczynski Noted for fixes. I'll update to test against a hard-coded CPU implementation.

**Comment by akshaysridhar** [comment]
@charleskawczynski Addressing the issue of incorrect indexing : as of commit 10c284, using `cuprint` to verify the populated array indices returns the following when running `runtests_gpu.jl` 
```
julia> include("test/runtests_gpu.jl")
[ Info: GPU Compatibility Tests
[ Info: CuArray
[ Info: CUDADevice{false, false}()
 3, @index(Group, Linear) output
 4, @index(Group, Linear) output
 1, @index(Group, Linear) output
 2, @index(Group, Linear) output
 4, loop index
 3, loop index
 1, loop index
 2, loop index
 ```
 This suggests that we are correctly populating the 4 array indices - I'll try to reproduce the issue above (i.e. 1 vs 1:4) with later commits to try to catch this error.

**Comment by charleskawczynski** [comment]
Hi @akshaysridhar, I just opened a [PR](https://github.com/CliMA/SurfaceFluxes.jl/pull/160) which prints out the results, and the results show that the main branch is still not populating the results correctly:

```julia
[ Info: GPU Compatibility Tests
[ Info: CuArray
 out_float32 = Float32[-2.526802 -99999.99 -99999.99 -99999.99]
 out_float64 = [-2.526841513506583 -99999.99 -99999.99 -99999.99]
```

https://buildkite.com/clima/surfacefluxes-ci/builds/1051#018dcc2b-2a19-49ee-a073-cd4fb9bb484c/395-403

Did you run your test on buildkite? If so, can you share a link? Or was it a local run?

**Comment by akshaysridhar** [comment]
The comment above referring to commit `10c284` was a local run on a `clima` node.
