### ISSUE TITLE
init fails on buildkite

### ISSUE THREAD

**Issue by szy21** [CliMA/SurfaceFluxes.jl#174]
The init environment fails for the latest main branch on buildkite: https://buildkite.com/clima/surfacefluxes-ci/builds/1106#_ It looks like some package issues. @akshaysridhar or @charleskawczynski Could you take a look? Thanks!

**Comment by charleskawczynski** [comment]
Hm, looks like we may just need to update climacommon? ClimaCore is now on `modules: climacommon/2024_05_27`. It looks like https://github.com/CliMA/SurfaceFluxes.jl/pull/172 was approved, but never merged due to some failure. I can try to rebase it.

**Comment by charleskawczynski** [comment]
Closed by #172

**Comment by szy21** [comment]
Ah, ok, thank you!
