### ISSUE TITLE
protect against zero devision given zero fluxes

### ISSUE THREAD

**Issue by yairchn** [CliMA/SurfaceFluxes.jl#26]
In the case of 'sc::Fluxes' and 'sc::FluxesAndFrictionVelocity' if the known fluxes are zero than 'local_lmo' in 394 and 'obukhov_length' in line 377 will result in zero devision. we should consider either returning a very large LMO or LMO=0 in these cases.

**Comment by akshaysridhar** [comment]
@yairchn I think https://github.com/CliMA/SurfaceFluxes.jl/pull/60 closed this issue.
