### ISSUE TITLE
Remove Conversion to Businger to guard against negative values?

### ISSUE THREAD

**Issue by odunbar** [CliMA/SurfaceFluxes.jl#31]
I've come across these functions
https://github.com/CliMA/SurfaceFluxes.jl/blob/63c2c4f53089c0ebf82c83a8544a972d37fa8077/src/UniversalFunctions.jl#L427-L434
These are used seemingly to extend `Gryanik` and `Grachev` implementations of `psi`/`phi` universal functions below zero. e.g.
https://github.com/CliMA/SurfaceFluxes.jl/blob/63c2c4f53089c0ebf82c83a8544a972d37fa8077/src/UniversalFunctions.jl#L405-L420
However, this conversion is pretty shakey - as changing the type also changes the parameter set used to create the function. 

1. What benefits does this have over extending the `zeta>0` case to `0` and using a constant or linear extension here
2. If we do wish to use `Businger`-type extension, we presumably want this to be related to the particular coefficients `a_m`,`a_h` etc that are used in the function for `zeta>0` rather than allowing possibility of drawing these from a random default set in `CLIMAParameters` (though this will only happen in other calls e.g. `Gryanik(::Businger)` as `Businger` has less parameters than `Gryanik`)

**Comment by charleskawczynski** [comment]
Closed by #41.
