### ISSUE TITLE
Non convergence 

### ISSUE THREAD

**Issue by kmdeck** [CliMA/SurfaceFluxes.jl#35]
Even with very high tolerance values, this script does not lead to a convergent M.O. solve:
```
using SurfaceFluxes
using Thermodynamics
using RootSolvers
using StaticArrays

using CLIMAParameters: AbstractEarthParameterSet
struct EarthParameterSet <: AbstractEarthParameterSet
end
FT = Float64
earth_param_set = EarthParameterSet()
T_atmos = 268.0
u_atmos = 2.0
q_atmos = 0.0
h_atmos = 30.0
ρ_atmos = 1.13
q_sfc = 0.0
T_sfc = 273.0
ts_sfc = Thermodynamics.PhaseEquil_ρTq(earth_param_set, ρ_atmos, T_sfc, q_sfc)
ts_in = Thermodynamics.PhaseEquil_ρTq(earth_param_set, ρ_atmos, T_atmos, q_atmos)

state_sfc = SurfaceFluxes.SurfaceValues(FT(0), SVector{2, FT}(0, 0), ts_sfc)
state_in = SurfaceFluxes.InteriorValues(h_atmos, SVector{2, FT}(u_atmos, 0), ts_in)

# State containers
kwargs = (; state_in, state_sfc, z0m = 1e-2, z0b = 1e-3)
sc = SurfaceFluxes.ValuesOnly{FT}(; kwargs...)
conditions = SurfaceFluxes.surface_conditions(
earth_param_set,
sc,
SurfaceFluxes.UniversalFunctions.Businger(); tol = RootSolvers.SolutionTolerance(1.0))
```

**Comment by LenkaNovak** [comment]
@yairchn @charleskawczynski we think this is because of the ρ difference [here](https://github.com/CliMA/SurfaceFluxes.jl/blob/main/src/SurfaceFluxes.jl#L445).

**Comment by yairchn** [comment]
These density values should different! 
If you need to estimate them we could use the existing `T_sfc` and `T_atmos` to get two densities. With `h_atmos =30.0` you can use hydrostatic balance to assume one density and estimate the other: 
`ρ=ρₛexp(-z/H)` with `H = 7km; z = h_atmos`

**Comment by LenkaNovak** [comment]
But what happens when buoyancy is 0? I found a note under Eq. 30 in the [SurfaceFluxDesignDoc](https://www.overleaf.com/project/616d983d2ac263356dc204dd) that this still needs to be addressed 🤔

**Comment by LenkaNovak** [comment]
[This](https://github.com/LenkaNovak/GFDL_idealized_GCM_Caltech/blob/862ebf728129cec5c1b5791c46662b364a03ff0d/idealized/src/atmos_param/monin_obukhov/monin_obukhov.f90#L143-L217) is how the FMS deals with it, in case it's useful.

**Comment by kmdeck** [comment]
> These density values should different! If you need to estimate them we could use the existing `T_sfc` and `T_atmos` to get two densities. With `h_atmos =30.0` you can use hydrostatic balance to assume one density and estimate the other: `ρ=ρₛexp(-z/H)` with `H = 7km; z = h_atmos`

this may be an silly question, but can the density at two different heights in the atmosphere at the same horizontal location not be equal by a physical law? can it ever arise that rho_sfc = rho_atmos, even just for a moment?

**Comment by yairchn** [comment]
> > These density values should different! If you need to estimate them we could use the existing `T_sfc` and `T_atmos` to get two densities. With `h_atmos =30.0` you can use hydrostatic balance to assume one density and estimate the other: `ρ=ρₛexp(-z/H)` with `H = 7km; z = h_atmos`
> 
> this may be an silly question, but can the density at two different heights in the atmosphere at the same horizontal location not be equal by a physical law? can it ever arise that rho_sfc = rho_atmos, even just for a moment?

@kmdeck - yes it could happen that the density is vertically uniform but it is much less likely than a uniform potential temperature.

**Comment by yairchn** [comment]
> [This](https://github.com/LenkaNovak/GFDL_idealized_GCM_Caltech/blob/862ebf728129cec5c1b5791c46662b364a03ff0d/idealized/src/atmos_param/monin_obukhov/monin_obukhov.f90#L143-L217) is how the FMS deals with it, in case it's useful.

You mean by coding it in fortran 😉 
It is not clear to me in this code what is defined as neutral, `Δθ ≈ FT(0)` or `Δρ ≈ FT(0)` I am guessing the former but definitely not both. So the same issue might arise there

**Comment by LenkaNovak** [comment]
Haha, there's a time and a place for Fortran 😏 . And yes they use `Δθ ≈ FT(0)` for `bstar`. And thanks for the pointers to the docs. I'll check them out!

**Comment by LenkaNovak** [comment]
Note that using `SF.jl` for variable transfer coefficients still breaks when using `SF.ValuesOnly` at times of neutral conditions due to the division by zero buoyancy flux during neutral conditions. Options were discussed with Akshay (using a total enthalpy flux, or having a conditional statement like the FMS). We will come back to this issue after the first AMIP, which will use constant transfer coefficients.

**Comment by yairchn** [comment]
> Note that using `SF.jl` for variable transfer coefficients still breaks when using `SF.ValuesOnly` at times of neutral conditions due to the division by zero buoyancy flux during neutral conditions. Options were discussed with Akshay (using a total enthalpy flux, or having a conditional statement like the FMS). We will come back to this issue after the first AMIP, which will use constant transfer coefficients.

this PR should solve this 
https://github.com/CliMA/SurfaceFluxes.jl/pull/36

**Comment by LenkaNovak** [comment]
On a roll, Yair! 🎉

**Comment by szy21** [comment]
@kmdeck @LenkaNovak Has this been fixed?

**Comment by szy21** [comment]
I think this has been fixed. I copied the non convergence case to #62 in case there is still a problem.
