### ISSUE TITLE
Examples for non convergence

### ISSUE THREAD

**Issue by szy21** [CliMA/SurfaceFluxes.jl#62]
This issue is to keep track of the non convergence issue. Maybe we can combine this with #35.

Trying to fix it by
- [x] Use relative or absolute tolerance #78 
- [x] Make initial guess dependent on stability regime #90 

1. `Float32 T_in = 275.624, T_sfc = 275.1768, q_in = 0.0044478197, q_sfc = 0.0044396375, u_in = (-19.07545f0, 16.88031f0), u_sfc = (0.0f0, 0.0f0), z0_m = 1.0e-5, z0_b = 1.0e-5, Δz = 15.000001, ΔDSEᵥ = 602.5625, ts_in = Thermodynamics.PhaseEquil{Float32}(1.2595116f0, 99902.82f0, 12337.749f0, 0.0044478197f0, 275.624f0), ts_sfc = Thermodynamics.PhaseEquil{Float32}(1.2544012f0, 99335.55f0, 11996.086f0, 0.0044396375f0, 275.1768f0), sol.root = NaN ERROR: LoadError: Unconverged Surface Fluxes.`

2. `Float32 T_in = 276.95068, T_sfc = 276.01752, q_in = 0.002202735, q_sfc = 0.0047157165, u_in = (-0.168524f0, -0.000566946f0), u_sfc = (0.0f0, 0.0f0), z0_m = 1.0e-5, z0_b = 1.0e-5, Δz = 15.000001, ΔDSEᵥ = 68.59375, ts_in = Thermodynamics.PhaseEquil{Float32}(1.2605726f0, 100331.47f0, 7956.4053f0, 0.002202735f0, 276.95068f0), ts_sfc = Thermodynamics.PhaseEquil{Float32}(1.2499729f0, 99303.92f0, 13258.002f0, 0.0047157165f0, 276.01752f0), sol.root = NaN ERROR: LoadError: Unconverged Surface Fluxes.` 

3. `maxiter reached in SurfaceFluxes.jl:
T_in = 290.8733, T_sfc = 290.97592, q_in = 0.012817842, q_sfc = 0.012941063, u_in = Float32[-14.154735, -5.1905923], u_sfc = Float32[0.0, 0.0], z0_m = 1.0e-5, z0_b = 1.0e-5, Δz = 15.000001, ΔDSEᵥ = -10.9375
ts_in(sc) = Thermodynamics.PhaseEquil{Float32}(1.1730341f0, 98689.72f0, 43302.703f0, 0.012817842f0, 290.8733f0)
ts_sfc(sc) = Thermodynamics.PhaseEquil{Float32}(1.1740736f0, 98819.375f0, 43671.336f0, 0.012941063f0, 290.97592f0), sol.root = -34996.734
`

4. `
maxiter reached in SurfaceFluxes.jl:
--
  | T_in = 291.46088, T_sfc = 291.5569, q_in = 0.013289474, q_sfc = 0.013432522, u_in = Float32[-13.526638, -8.794365], u_sfc = Float32[0.0, 0.0], z0_m = 1.0e-5, z0_b = 1.0e-5, Δz = 15.000001, ΔDSEᵥ = -12.90625
  | ts_in(sc) = Thermodynamics.PhaseEquil{Float32}(1.1698402f0, 98647.89f0, 44855.285f0, 0.013289474f0, 291.46088f0)
  | ts_sfc(sc) = Thermodynamics.PhaseEquil{Float32}(1.1708081f0, 98770.55f0, 45266.523f0, 0.013432522f0, 291.5569f0)
  | , sol.root = -34057.94
`

5. `maxiter reached in SurfaceFluxes.jl:
 T_in = 276.25174, T_sfc = 276.38446, q_in = 0.0048752176, q_sfc = 0.004953378, u_in = Float32[-41.34482, -23.609104], u_sfc = Float32[0.0, 0.0], z0_m = 1.0e-5, z0_b = 1.0e-5, Δz = 15.000001, ΔDSEᵥ = -18.96875
ts_in(sc) = Thermodynamics.PhaseEquil{Float32}(1.2182463f0, 96874.9f0, 13805.914f0, 0.0048752176f0, 276.25174f0)
ts_sfc(sc) = Thermodynamics.PhaseEquil{Float32}(1.2197124f0, 97042.68f0, 14087.365f0, 0.004953378f0, 276.38446f0)
, sol.root_history = Float32[-1.0, -26.837957, -1725.5912, -169877.83, -188948.84, -188936.05, -188945.89, -188935.86, -188945.9, -188935.86, -188945.9], sol.err_history = Float32[212108.39, 212108.39, 194393.42, 187415.3, 19070.125, -12.796875, 9.84375, -10.03125, 10.046875, -10.046875, 10.046875]`

6. `
maxiter reached in SurfaceFluxes.jl:
T_in = 282.31366, T_sfc = 280.76575, q_in = 0.0026684932, q_sfc = 0.006637053, u_in = Float32[-0.75088084, -0.09317328], u_sfc = Float32[0.0, 0.0], z0_m = 1.0e-5, z0_b = 1.0e-5, Δz = 15.000001, ΔDSEᵥ = 69.96875
ts_in(sc) = Thermodynamics.PhaseEquil{Float32}(1.2317619f0, 99965.086f0, 12921.355f0, 0.0026684932f0, 282.31366f0)
ts_sfc(sc) = Thermodynamics.PhaseEquil{Float32}(1.214932f0, 98294.87f0, 21252.703f0, 0.006637053f0, 280.76575f0), sol.root = NaN
`
7.
```
using SurfaceFluxes
using Thermodynamics
using RootSolvers
using StaticArrays

using CLIMAParameters: AbstractEarthParameterSet
struct EarthParameterSet <: AbstractEarthParameterSet
end
FT = Float64
earth_param_set = EarthParameterSet()
T_atmos = 268.0
u_atmos = 2.0
q_atmos = 0.0
h_atmos = 30.0
ρ_atmos = 1.13
q_sfc = 0.0
T_sfc = 273.0
ts_sfc = Thermodynamics.PhaseEquil_ρTq(earth_param_set, ρ_atmos, T_sfc, q_sfc)
ts_in = Thermodynamics.PhaseEquil_ρTq(earth_param_set, ρ_atmos, T_atmos, q_atmos)

state_sfc = SurfaceFluxes.SurfaceValues(FT(0), SVector{2, FT}(0, 0), ts_sfc)
state_in = SurfaceFluxes.InteriorValues(h_atmos, SVector{2, FT}(u_atmos, 0), ts_in)

# State containers
kwargs = (; state_in, state_sfc, z0m = 1e-2, z0b = 1e-3)
sc = SurfaceFluxes.ValuesOnly{FT}(; kwargs...)
conditions = SurfaceFluxes.surface_conditions(
earth_param_set,
sc,
SurfaceFluxes.UniversalFunctions.Businger(); tol = RootSolvers.SolutionTolerance(1.0))
```

**Comment by akshaysridhar** [comment]
Both these cases are classified as stable boundary layers in our code; I think the solution here : https://github.com/CliMA/SurfaceFluxes.jl/blob/0e3aaa6720bf5fd0c710b26ed568f7ecd009895c/src/SurfaceFluxes.jl#L420-L448 is one option that generally addresses \zeta > 0 cases. (The equations have been added to the design docs as well)

**Comment by szy21** [comment]
@akshaysridhar I just added an example with thermo states input. We can test and add the analytical solution whenever you have time.

**Comment by akshaysridhar** [comment]
Using the experimental branch for the stable analytical solution; I get the following result using the input variables listed in (4)
``` 
SF.surface_conditions(param_set, sc, sch; maxiter, soltype = RS.VerboseSolution())
----------------------- SurfaceFluxConditions
L_MO                   = 1596.6465
Sensible Heat Flux     = -20.259878
Latent Heat Flux       = -0.6949584
Buoyancy Flux          = -0.0005714346
Friction velocity u⋆   = 0.71424234
C_drag                 = 0.0007862642
C_heat                 = 0.001061365
evaporation            = -2.7747842e-7
-----------------------
```

**Comment by szy21** [comment]
We have non convergence in ClimaAtmos for the unstable regime too. I have updated the issue.

**Comment by charleskawczynski** [comment]
Just to note, it might be good to add some sort of quantification of converged vs non-converged cases in a test where we cast a wider net over the input variables, like what we do in the Thermodynamics [dev docs](https://clima.github.io/Thermodynamics.jl/dev/DevDocs/)

**Comment by szy21** [comment]
I noticed that for iterative solution for the stable regime, if I use L_MO_init = 1 rather than the default -1, it will converge. @akshaysridhar Maybe we can make L_MO_init dependent on \Delta DSE_v (instead of being defined by users)?

**Comment by akshaysridhar** [comment]
> I noticed that for iterative solution for the stable regime, if I use L_MO_init = 1 rather than the default -1, it will converge. @akshaysridhar Maybe we can make L_MO_init dependent on \Delta DSE_v (instead of being defined by users)?
#89 tracks this

**Comment by akshaysridhar** [comment]
https://github.com/CliMA/SurfaceFluxes.jl/pull/110 demonstrates working solutions for each of these examples, closing this issue. If further edge cases are identified we can track them in new issues.
